repos:
  # Generic pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0  # Use the latest version from https://github.com/pre-commit/pre-commit-hooks/releases
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-case-conflict
      - id: trailing-whitespace
        exclude: ^pkg/swagger/
      - id: end-of-file-fixer
        exclude: ^pkg/swagger/
      - id: mixed-line-ending
        exclude: ^pkg/swagger/
      - id: check-added-large-files
        name: check for added large files
        description: Prevents giant files from being committed
        args: ['--maxkb=500']

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.18.1
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.28.0  # Use the latest version
    hooks:
      - id: gitleaks

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30 
    hooks:
      - id: helmlint