{{- if .Values.podDisruptionBudget.enabled }}
{{- if eq (.Values.replicaCount | int) 1 }}
{{- fail "PodDisruptionBudget is not supported with replicaCount=1. Set podDisruptionBudget.enabled=false." }}
{{- end }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tka.fullname" . }}
  labels:
    {{- include "tka.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tka.selectorLabels" . | nindent 6 }}
{{- end }}
