apiVersion: v1
kind: Service
metadata:
  name: {{ include "tka.fullname" . }}
  labels:
    {{- include "tka.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.tka.health.port }}
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "tka.selectorLabels" . | nindent 4 }}
