apiVersion: v1
kind: Service
metadata:
  name: {{ include "tka.fullname" . }}
  labels:
    {{- include "tka.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
    - port: {{ .Values.service.metricsPort }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "tka.selectorLabels" . | nindent 4 }}
