{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tka.fullname" . }}
  labels:
    {{- include "tka.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "tka.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: https
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
    {{- if eq (.Values.tka.tailscale.port | int) 443 }}
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    {{- else }}
    scheme: http
    {{- end }}
{{- end }}
