apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "staticpages.fullname" . }}-cm
  labels:
    {{- include "staticpages.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- include "staticpages.config.cm" . | trim | nindent 4 }}
