{{- if .Values.staticpages.ingress.enabled -}}
{{- $fullName := include "staticpages.fullname" . -}}
{{- $apiPort := .Values.staticpages.service.apiPort -}}
{{- $proxyPort := .Values.staticpages.service.proxyPort -}}
{{- if and .Values.staticpages.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.staticpages.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.staticpages.ingress.annotations "kubernetes.io/ingress.class" .Values.staticpages.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "staticpages.labels" . | nindent 4 }}
  {{- with .Values.staticpages.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.staticpages.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.staticpages.ingress.className }}
  {{- end }}
  {{- if .Values.staticpages.ingress.tls }}
  tls:
    {{- range .Values.staticpages.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
    - hosts:
        {{- range .Values.configs.pages }}
        - {{ .domain | quote }}
        {{- end }}
      secretName: pages-proxy-tls
  {{- end }}
  rules:
    {{- range .Values.staticpages.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /upload
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-api
                port:
                  number: {{ $apiPort }}
              {{- else }}
              serviceName: {{ $fullName }}-api
              servicePort: {{ $apiPort }}
              {{- end }}
    {{- end }}
    {{- range .Values.configs.pages }}
    - host: {{ .domain | quote }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}-proxy
                port:
                  number: {{ $proxyPort }}
              {{- else }}
              serviceName: {{ $fullName }}-proxy
              servicePort: {{ $proxyPort }}
              {{- end }}
    {{- end }}
{{- end }}
