apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  labels:
    {{- include "staticpages.labels" . | nindent 4 }}
stringData:
    app-id: {{ .Values.s3.appId | quote }}
    s3-secret: {{ .Values.s3.secret | quote }}