{{- if .Values.staticpages.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "staticpages.serviceAccountName" . }}
  labels:
    {{- include "staticpages.labels" . | nindent 4 }}
  {{- with .Values.staticpages.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
